#server.port=8000
#spring.application.name=config-service
#spring.cloud.config.label=master
#spring.cloud.config.server.git.uri=https://github.com/15536367173/zhangtianyang-test
#spring.cloud.config.server.git.username=15536367173@163.com
#spring.cloud.config.server.git.password=mjlhhazj0813!
#spring.cloud.config.server.git.search-paths=config-server
server:
  port: 8000
spring:
  application:
    name: config-service
  cloud:
    config:
      label: master
      server:
        git:
          username: 15536367173@163.com
          password: mjlhhazj0813!
          search-paths: config-service